name: github action test 1
run-name: ${{ github.actor }} is running Github-Actions 🚀
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  job-ga-1:
    runs-on: ubuntu-latest
    steps:
      - name: step breaker
        run: |
          # Check if the number is even (modulus 2 equals 0)
          if [ ${{ secrets.BREAKER }} = "true" ]; then
            exit 1
          else
            echo "ok"
          fi
      - name: step 1 
        run: echo 'hello there!'
      - name: step 2 
        run: echo 'hello there too!'
      - name: step 3 
        run: echo 'hello there tree!'
